language: python
python:
    - 2.6
    - 2.7
    - 3.3
env:
    - DJANGO=1.4 DATABASE_URL='sqlite://localhost/:memory:'
    - DJANGO=1.4 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test'
    - DJANGO=1.4 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test'
    - DJANGO=1.5 DATABASE_URL='sqlite://localhost/:memory:'
    - DJANGO=1.5 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test'
    - DJANGO=1.5 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test'

before_script:
  - sh -c "if [ '$DATABASE_URL' = 'postgres://postgres@127.0.0.1/djangocms_test' ]; then psql -c 'DROP DATABASE IF EXISTS djangocms_test;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'postgres://postgres@127.0.0.1/djangocms_test' ]; then psql -c 'create database djangocms_test;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'mysql://root@127.0.0.1/djangocms_test' ]; then mysql -e 'create database IF NOT EXISTS djangocms_test CHARACTER SET utf8 COLLATE utf8_general_ci;'; fi"

install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - pip install -q -r "test_requirements/django-$DJANGO.txt" 
    - if [ $DATABASE_URL == 'postgres://postgres@127.0.0.1/djangocms_test' ]; then pip install -q psycopg2 ; fi
    - if [ $DATABASE_URL == 'mysql://root@127.0.0.1/djangocms_test' ]; then pip install -q mysql-python ; fi
script:
    coverage run --rcfile=.coverage.rc develop.py test --migrate

after_success:
    coveralls --config_file=.coverage.rc --coveralls_yaml=.coveralls.yml

notifications:
    email:
        recipients:
          - digi@treepy.com
        on_success: never
        on_failure: always
    irc:
        - "irc.freenode.org#django-cms"
        - "irc.freenode.org#django-cms-sprint"


matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4 DATABASE_URL='sqlite://localhost/:memory:'
    - python: 3.3
      env: DJANGO=1.4 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test'
    - python: 3.3
      env: DJANGO=1.4 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test'
    - python: 3.3
      env: DJANGO=1.5 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test'
