language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
env:
    - DJANGO="django>=1.3,<1.4"
    - DJANGO="django>=1.4,<1.5"
install:
    - pip install -q $DJANGO django-mptt==0.5.1 django-reversion==1.6 django-classy-tags==0.3.4.1 django-sekizai==0.6.1 html5lib==0.95 jinja2==2.6 PIL==1.1.7 pygments==1.5 south==0.7.5 sphinx==1.1.3 argparse
script:
    python runtests.py
notifications:
    email:
        recipients:
          - digi@treepy.com
        on_success: never
        on_failure: always
    irc:
        - "irc.freenode.org#django-cms"
        - "irc.freenode.org#django-cms-sprint"

