language: python

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7

sudo: false

addons:
  apt:
    packages:
    - enchant

env:
  global:
    # coveralls finalangel
    - secure: HhAmAArxQg4FEufv40M6nxwSnCz2BE3QkLln8ux8DxgZrs7ENDZEMHrcCeH3QXshAnowzpgmEMIiZXfQZ35tBC7uWyq4CUgVrbxv1SNPpjDmAgb21nFEZRJR88+erpkd9H6oYXm4JWOMc3f/FkR9JjugFCrcHiHc4zGLCsmLNNQ=
    sauce labs username
    - secure: g40WBtWZyN0sGwEZnBHZPKF3J9/e+y/ncftTI6U5iNM+pVa62dSVoZsyC9YDxZ7wbK+WMcYez5MNtYbbFQD+kjBLeUbpfJ9LnOwEtZU0bl3FOYhRJZmBfWXBKyWAIx7CIspkU64jaVGgC4F7dYptileC94rMGHsYzL3nqJ4XnUY=
    sauce labs access token
    - secure: Zos3su5QFeEwDCuibiE4nejeDgjgvw59IcEiWTw2L9tzZBBvaXe0plMDum7AeLIeNalYFericsIAegNoix/jfxOC92Nyq2Izh15vk08YvZCLFMUVjtg+ENb84/Km5018VVU6W+7HmfJDDN0fvHzdjHoBLN99BWSQ7XddHQWUs7g=
  matrix:
    - DJANGO=1.9 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='customuserapp.User'
    - DJANGO=1.8 DATABASE_URL='sqlite://localhost/:memory:' SELENIUM=0 MIGRATE_OPTION='--migrate'
    - DJANGO=1.8 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0
    - DJANGO=1.8 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=0 MIGRATE_OPTION='--migrate'
    - DJANGO=1.8 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='emailuserapp.EmailUser'
    - DJANGO=1.8 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='customuserapp.User'
    - FRONTEND=1 UNIT=1
    - FRONTEND=1 LINT=1

before_script:
  - pip freeze
  - sh -c "if [ '$DATABASE_URL' = 'postgres://postgres@127.0.0.1/djangocms_test' ];
    then psql -c 'DROP DATABASE IF EXISTS djangocms_test;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'postgres://postgres@127.0.0.1/djangocms_test' ];
    then psql -c 'create database djangocms_test;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'mysql://root@127.0.0.1/djangocms_test' ]; then mysql
    -e 'create database IF NOT EXISTS djangocms_test CHARACTER SET utf8 COLLATE utf8_general_ci;';
    fi"

before_install:
  - "export DISPLAY=:99.0"
  # xvfb is started in this way to ensure the screen size is 1280x1024x8
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x8"
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  # match would equal 0
  - "echo $TRAVIS_COMMIT_MSG | grep '\[use saucelabs\]'; export SKIP_SAUCE_LABS=$?; true"

install:
  - if [ "$FRONTEND" != 1 ]; then pip install -r "test_requirements/django-$DJANGO.txt"; fi
  # - if [ "$FRONTEND" == 1 ]; then rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && source ~/.nvm/nvm.sh && nvm install 0.12); fi
  - if [ "$FRONTEND" == 1 ]; then npm install -g npm@2; fi
  - if [ "$FRONTEND" == 1 ]; then npm install -g gulp@3.9.0; fi
  - if [ "$FRONTEND" == 1 ]; then npm install; fi
  - if [ "$FRONTEND" != 1 ] && [ "$DATABASE_URL" == 'postgres://postgres@127.0.0.1/djangocms_test' ]; then pip install psycopg2 ; fi
  - if [ "$FRONTEND" != 1 ] && [ "$DATABASE_URL" == 'mysql://root@127.0.0.1/djangocms_test' ]; then pip install mysqlclient ; fi

script:
  - if [ "$FRONTEND" == 1 ] && [ "$UNIT" == 1 ]; then gulp tests:unit; fi;
  - if [ "$FRONTEND" == 1 ] && [ "$LINT" == 1 ]; then gulp lint; fi;
  - if [ "$FRONTEND" != 1 ]; then coverage run --parallel-mode manage.py test $MIGRATE_OPTION; fi;
  - if [ "$FRONTEND" != 1 ]; then coverage combine; fi;

after_success: coveralls

notifications:
  irc:
    - irc.freenode.org#django-cms
    - irc.freenode.org#django-cms-sprint
  webhooks:
    - http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/

matrix:
  exclude:

    - python: 3.3
      env: DJANGO=1.8 DATABASE_URL='sqlite://localhost/:memory:' SELENIUM=0 MIGRATE_OPTION='--migrate'
    - python: 3.3
      env: DJANGO=1.8 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0
    - python: 3.3
      env: DJANGO=1.8 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=0 MIGRATE_OPTION='--migrate'
    - python: 3.3
      env: DJANGO=1.8 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='emailuserapp.EmailUser'

    - python: 2.7
      env: DJANGO=1.9 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='customuserapp.User'
    - python: 3.3
      env: DJANGO=1.9 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='customuserapp.User'
    - python: 3.5
      env: DJANGO=1.9 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='customuserapp.User'

    - python: 3.3
      env: FRONTEND=1 UNIT=1
    - python: 3.3
      env: FRONTEND=1 LINT=1
    - python: 3.4
      env: FRONTEND=1 UNIT=1
    - python: 3.4
      env: FRONTEND=1 LINT=1
    - python: 3.5
      env: FRONTEND=1 UNIT=1
    - python: 3.5
      env: FRONTEND=1 LINT=1

  allow_failures:
    - python: 2.7
      env: DJANGO=1.8 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0

    - python: 3.3
      env: DJANGO=1.8 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0

    - python: 3.4
      env: DJANGO=1.8 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0

    - python: 3.5
      env: DJANGO=1.8 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0

    - python: 3.4
      env: DJANGO=1.9 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='customuserapp.User'

  fast_finish: true
